### ISSUE TITLE
Remove generation of deprecation notice message (state and output) 

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/actions#75]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Warning: The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

This can generally be done by bumping actions/core to 1.10.0, see https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md#1100

**Actions to be updated (non exhaustive list)**

- [x] list-branches: change the call to "set-output" https://github.com/bonitasoft/actions/blob/v1.3.1/packages/list-branches/action.yml#L33 #84
- [x] notify-slack. Composite action calling slackapi/slack-github-action@v1.17.0 (https://github.com/bonitasoft/actions/blob/v1.3.1/packages/notify-slack/action.yml#L21). Bump action to get the fix: https://github.com/slackapi/slack-github-action/releases/tag/v1.23.0 #89 + setup a demo workflow to test the slack notification in  a test channel (workflow dispatch) #88
- [x] pr-diff-checker. #66
- [x] surge-preview-tools #86

**Comment by tbouffard** [comment]
All tasks are completed, so closing
